In [2]:
%cd ../

/home/users/dmoreno2016/VisionTransformers

In [3]:
import pandas as pd

In [7]:
path_data = 'data/lightcurves/plasticc/raw'
target_name = 'true_target'
df_metadata_test = pd.read_csv(f'{path_data}/unblinded_test_set_metadata.csv')
df_metadata_test = df_metadata_test[~df_metadata_test[target_name].isin([991, 992, 993, 994])]
df_metadata_test

,object_id,ra,decl,ddf_bool,hostgal_specz,hostgal_photoz,hostgal_photoz_err,distmod,mwebv,target,...,true_rv,true_av,true_peakmjd,libid_cadence,tflux_u,tflux_g,tflux_r,tflux_i,tflux_z,tflux_y
0,13,34.4531,-5.2295,1,0.305,0.319,0.054,41.112,0.019,0,...,0.0,0.0,60499.461,124,0.0,0.0,0.0,0.0,0.0,0.0
1,14,33.3984,-4.3311,1,-9.000,0.632,0.018,42.877,0.018,0,...,0.0,0.0,59792.121,120,0.0,0.0,0.0,0.0,0.0,0.0
2,17,348.5294,-61.7554,1,-9.000,0.830,0.060,43.600,0.016,0,...,0.0,0.0,60543.566,85,0.0,0.0,0.0,0.0,0.0,0.0
3,23,34.8047,-5.8292,1,-9.000,0.653,0.148,42.964,0.023,0,...,0.0,0.0,60137.480,97,0.0,0.0,0.0,0.0,0.0,0.0
4,34,351.3214,-64.1987,1,0.456,0.462,0.012,42.054,0.023,0,...,0.0,0.0,60245.078,68,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492885,130787966,67.5000,-23.8063,0,-9.000,0.449,0.995,41.984,0.036,0,...,0.0,0.0,60176.078,35877,0.0,0.0,0.0,0.0,0.0,0.0
3492886,130787971,98.7891,-32.9749,0,-9.000,0.673,0.061,43.042,0.083,0,...,0.0,0.0,60659.273,47200,0.0,0.0,0.0,0.0,0.0,0.0
3492887,130787974,133.9453,-21.5423,0,-9.000,0.121,0.009,38.760,0.136,0,...,0.0,0.0,60261.289,21691,0.0,0.0,0.0,0.0,0.0,0.0
3492888,130788053,199.1602,-0.8953,0,-9.000,0.429,0.262,41.863,0.028,0,...,0.0,0.0,60143.660,23710,0.0,0.0,0.0,0.0,0.0,0.0
3492889,130788054,10.0195,-32.7972,0,-9.000,0.363,0.734,41.433,0.013,0,...,0.0,0.0,60462.855,38234,0.0,0.0,0.0,0.0,0.0,0.0