In [1]:
%cd ../

/home/users/dmoreno2016/VisionTransformers

In [2]:
import mlflow
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [3]:
mlflow.set_tracking_uri("file:./results/elasticc_1/ml-runs")

In [7]:
data_name =  'elasticc_1'
experiment_name = f"ft_classification/{data_name}/testing"

experiment = mlflow.get_experiment_by_name(experiment_name)
if experiment:
    experiment_id = experiment.experiment_id
    print(f"Experiment ID for '{experiment_name}': {experiment_id}")
else:
    print(f"Experiment '{experiment_name}' not found.")

runs = mlflow.search_runs(experiment_ids=[experiment_id])

# Filtrar las corridas que coincidan con los par√°metros especificados
filtered_runs = runs[
    (runs['params.imgs_params/input_type'] == 'overlay')
]

failed = filtered_runs[filtered_runs.status == 'FAILED']
running = filtered_runs[filtered_runs.status == 'RUNNING']
finished = filtered_runs[filtered_runs.status == 'FINISHED']

print(len(failed))
print(len(running))
print(len(finished))

grouped_df = finished.groupby([
    'params.imgs_params/fig_params/linewidth',
    'params.imgs_params/fig_params/markersize',
    'params.imgs_params/input_type',
    'params.imgs_params/use_err',
    'params.training/lr',
])['metrics.f1/test'].agg(['mean', 'std']).reset_index()

grouped_df.rename(columns={'mean': 'metrics.f1/test_mean', 'std': 'metrics.f1/test_std'}, inplace=True)

print(f'Number experiments: {len(grouped_df)}')

grouped_df = grouped_df.sort_values(by=['metrics.f1/test_mean'], ascending=False)
grouped_df.head(10)

Experiment ID for 'ft_classification/elasticc_1/testing': 614122580949636032
0
0
80
Number experiments: 80

,params.imgs_params/fig_params/linewidth,params.imgs_params/fig_params/markersize,params.imgs_params/input_type,params.imgs_params/use_err,params.training/lr,metrics.f1/test_mean,metrics.f1/test_std
7,0.5,2.0,overlay,True,5e-06,0.665343,NaN
39,1.0,5.0,overlay,True,5e-06,0.664905,NaN
19,0.5,5.0,overlay,True,5e-06,0.663084,NaN
75,2.0,4.0,overlay,True,5e-06,0.657780,NaN
50,1.5,3.0,overlay,True,5e-05,0.657710,NaN
47,1.5,2.0,overlay,True,5e-06,0.657171,NaN
70,2.0,3.0,overlay,True,5e-05,0.657153,NaN
35,1.0,4.0,overlay,True,5e-06,0.656982,NaN
55,1.5,4.0,overlay,True,5e-06,0.656811,NaN
3,0.5,1.0,overlay,True,5e-06,0.656384,NaN

In [8]:
data_name =  'elasticc_1'
experiment_name = f"ft_classification/{data_name}/testing"

experiment = mlflow.get_experiment_by_name(experiment_name)
if experiment:
    experiment_id = experiment.experiment_id
    print(f"Experiment ID for '{experiment_name}': {experiment_id}")
else:
    print(f"Experiment '{experiment_name}' not found.")

runs = mlflow.search_runs(experiment_ids=[experiment_id])

# Filtrar las corridas que coincidan con los par√°metros especificados
filtered_runs = runs[
    (runs['params.imgs_params/input_type'] == '6grid')
]

failed = filtered_runs[filtered_runs.status == 'FAILED']
running = filtered_runs[filtered_runs.status == 'RUNNING']
finished = filtered_runs[filtered_runs.status == 'FINISHED']

print(len(failed))
print(len(running))
print(len(finished))

grouped_df = finished.groupby([
    'params.imgs_params/fig_params/linewidth',
    'params.imgs_params/fig_params/markersize',
    'params.imgs_params/input_type',
    'params.imgs_params/use_err',
    'params.training/lr',
])['metrics.f1/test'].agg(['mean', 'std']).reset_index()

grouped_df.rename(columns={'mean': 'metrics.f1/test_mean', 'std': 'metrics.f1/test_std'}, inplace=True)

print(f'Number experiments: {len(grouped_df)}')

grouped_df = grouped_df.sort_values(by=['metrics.f1/test_mean'], ascending=False)
grouped_df.head(10)

Experiment ID for 'ft_classification/elasticc_1/testing': 614122580949636032

12
12
36
Number experiments: 36

,params.imgs_params/fig_params/linewidth,params.imgs_params/fig_params/markersize,params.imgs_params/input_type,params.imgs_params/use_err,params.training/lr,metrics.f1/test_mean,metrics.f1/test_std
2,0.5,1.0,6grid,True,5e-05,0.653142,NaN
13,0.5,5.0,6grid,True,5e-05,0.645784,NaN
10,0.5,4.0,6grid,True,5e-05,0.644190,NaN
18,1.0,2.0,6grid,True,5e-05,0.642295,NaN
5,0.5,2.0,6grid,True,5e-05,0.641253,NaN
34,1.5,4.0,6grid,True,5e-05,0.640866,NaN
22,1.0,4.0,6grid,True,5e-05,0.639665,NaN
7,0.5,3.0,6grid,True,5e-05,0.639365,NaN
25,1.0,5.0,6grid,True,5e-05,0.638616,NaN
29,1.5,2.0,6grid,False,5e-06,0.636192,NaN